spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://db:3306/iam
    username: iam
    password: iam@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: redis

  redis:
    host: hair-redis
    port: 6379
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
    timeout: 2000ms

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8443
  ssl:
    key-store: classpath:new_keystore.p12
    key-store-password: iam123
    key-store-type: PKCS12
    key-alias: new_alias